# -*- coding: utf-8 -*-
"""Currency_Converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDZFTE7GsMsS_3BRfnmCfH67gNj-L2vO
"""

#install
!pip install freecurrencyapi

#imports
import freecurrencyapi
import sys

#set up the client
client = freecurrencyapi.Client(#API_KEY)

#currency converter function
def currency_converter(base_currency, target_currency):
  result = client.latest(base_currency.upper())['data'][target_currency.upper()]
  return result

#list of currencies
currency_dictionary = client.currencies()["data"]
currency_list = list(currency_dictionary.keys())
print(currency_list)

#shell arguments
if __name__ == "__main__":
  args = sys.argv
  #converts two specified currencies
  if len(args) == 3 and str(args[1]).upper() in currency_list and str(args[2]).upper() in currency_list:
    base_currency = args[1]
    target_currency = args[2]
  #default: EUR -> USD conversion
  elif len(args) == 1:
    base_currency = "EUR"
    target_currency = "USD"
  else:
    raise Exception("error")
  result = currency_converter(base_currency, target_currency)
  print(f"{base_currency} -> {target_currency} : {result}")